### ISSUE TITLE
Suggestion/Question for devnum

### ISSUE THREAD

**Issue by andrewchambers** [andrewchambers/fspec-tools#14]
How best to get the devnum for a given dev major/minor. I'm having a bit of trouble finding how to get it?

To expand on this, it seems quite annoying to get this, but ls -la shows major/minor by default. Perhaps devnum should allow a comma separated pair in the spec.

**Comment by michaelforney** [comment]
The reason I suggested devnum as opposed to devmajor and devminor is that all POSIX really specifies is the device number. The `major`, `minor`, and `makedev` macros are non-POSIX and found in sys/types.h on BSD, and sys/sysmacros.h on Linux, but BSDs don't have sys/sysmacros.h.

You can get the device number from `st_rdev` in struct stat. The `ls -l` format output just says

> The device info field shall contain implementation-defined information associated with the device in question.

so it's not really suitable for parsing major and minor numbers.

**Comment by andrewchambers** [comment]
Yeah, I guess my problem is I want to go from something like the arch linux chroot guide, which uses mknod, to an fspec. Closing for now.
