### ISSUE TITLE
0001-fspec-archive-sanity.test cpio portion fails

### ISSUE THREAD

**Issue by andrewchambers** [andrewchambers/fspec-tools#17]

**Comment by michaelforney** [comment]
I think this is a bug in libarchive:

https://github.com/libarchive/libarchive/blob/master/libarchive/archive_write_set_format_cpio.c#L351

This line should use `archive_entry_rdev(entry)`, not `archive_entry_dev(entry)`.

**Comment by andrewchambers** [comment]
wow, that being there for 9 years doesn't inspire confidence. I suppose initramfs is the only place you would typically use this, and libarchive is mostly a freebsd thing.

**Comment by andrewchambers** [comment]
Resolving this by defaulting to cpio_newc, In the unlikely event someone complains they can add a flag to choose the variant, and bother with that annoying problem of fixing it upstream and waiting.
