### ISSUE TITLE
Absolute or relative path names

### ISSUE THREAD

**Issue by michaelforney** [andrewchambers/fspec-tools#23]
Currently, we are mostly using relative names for filenames, like

```
bin/sh
type=reg
mode=0755
```

However, we should consider if the file name should always be absolute, or if we should allow both.

Here are some advantages of absolute path names:
- We can support comments, since all paths begin with `/`, and `#` is not valid in an attribute name.
- We may want to set the mode of `/` itself in the filesystem, and `.` is kind of awkward.

If a source attribute wasn't present for `type=reg`, we'd still probably want to treat the paths as relative to the manifest.

**Comment by andrewchambers** [comment]
One thing Is it means is that \n\n is no longer needed for splitting records. I think this may make it easier to concatenate specs without worrying about trailing newlines.

It maybe has implications for fromtar, and what to do it / is missing. Overall I wouldn't mind absolute as it doesn't break my use cases.

**Comment by andrewchambers** [comment]
@michaelforney I thought some more, and almost feel comments should just be an application thing they can filter with sed. Is there a reason why the / path can't be specified instead of . already?
