### ISSUE TITLE
fspec-tar does not match spec for manifest paths.

### ISSUE THREAD

**Issue by andrewchambers** [andrewchambers/fspec-tools#8]
According to the spec source paths are relative to the manifest path.

>  If not present, the entry name is used, relative to the directory containing the manifest.

Currently fspec-tar uses stdin, so has no way of knowing the manifest path (other than cwd). We could add:

```
$ fspec-tar [$PATH ...]
```
To give us reference paths, we could possibly add a --relative-to option too.

**Comment by michaelforney** [comment]
Yeah, I think the tools should accept a manifest on the command-line and use stdin if not given. In the case where the manifest comes from stdin, probably the sanest thing to do is to treat the paths as relative to the current working directory.

I think an option to change the base directory for source file lookups makes sense, but I'd prefer not to use --long-options.

**Comment by michaelforney** [comment]
This is fixed by 9119f4d3c8336f442db07c1904117444377caba4, right?

**Comment by andrewchambers** [comment]
Think so.
